[mysql]
DB_USER = "freedb_davidscatterday"
DB_PASSWORD = "KC55*RM*F8ujyfn"
DB_HOST = "sql.freedb.tech"
DB_PORT = "3306"
DB_NAME = "freedb_NYCtest"

[passwords]
david_scatterday = "abc123"
mike = "prointel123"
adam = "prointel456"